"""
Code Generation Utilities and Templates.

Provides templates and utilities for consistent code generation
across development agents.
"""

from typing import Dict, Any, List, Optional
import re

# ============================================================================
# Backend Templates (Python/FastAPI)
# ============================================================================

BACKEND_MAIN_TEMPLATE = '''"""
{module_name} - FastAPI Application
Generated by Agentic PRD Factory
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{app_title}",
    description="{description}",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

{router_imports}

{router_includes}

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {{"status": "healthy"}}
'''

BACKEND_ROUTER_TEMPLATE = '''"""
{router_name} Router
{description}
"""

from fastapi import APIRouter, HTTPException, Depends
from typing import List, Optional
{schema_imports}

router = APIRouter(prefix="/{prefix}", tags=["{tag}"])

{endpoints}
'''

BACKEND_SCHEMA_TEMPLATE = '''"""
{schema_name} Pydantic Schemas
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

{schemas}
'''

BACKEND_MODEL_TEMPLATE = '''"""
{model_name} SQLAlchemy Models
"""

from sqlalchemy import Column, Integer, String, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base

{models}
'''

# ============================================================================
# Frontend Templates (React/TypeScript)
# ============================================================================

FRONTEND_COMPONENT_TEMPLATE = '''/**
 * {component_name}
 * {description}
 * Generated by Agentic PRD Factory
 */

import React from 'react';
{imports}

interface {component_name}Props {{
{props_interface}
}}

export const {component_name}: React.FC<{component_name}Props> = ({{ {props_destructure} }}) => {{
{component_body}
}};

export default {component_name};
'''

FRONTEND_HOOK_TEMPLATE = '''/**
 * {hook_name}
 * {description}
 */

import {{ useState, useEffect, useCallback }} from 'react';
{imports}

{types}

export function {hook_name}({params}): {return_type} {{
{hook_body}
}}
'''

FRONTEND_API_TEMPLATE = '''/**
 * API client for {feature_name}
 */

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8000';

{api_functions}
'''

# ============================================================================
# Test Templates
# ============================================================================

PYTEST_TEMPLATE = '''"""
Tests for {module_name}
Generated by Agentic PRD Factory
"""

import pytest
from fastapi.testclient import TestClient
{imports}

{fixtures}

{test_classes}
'''

JEST_TEMPLATE = '''/**
 * Tests for {component_name}
 */

import React from 'react';
import {{ render, screen, fireEvent, waitFor }} from '@testing-library/react';
import {{ {component_name} }} from './{component_name}';

{test_cases}
'''

PLAYWRIGHT_TEMPLATE = '''/**
 * E2E Tests for {feature_name}
 */

import {{ test, expect }} from '@playwright/test';

{page_objects}

{test_cases}
'''

# ============================================================================
# DevOps Templates
# ============================================================================

DOCKERFILE_BACKEND_TEMPLATE = '''# Backend Dockerfile
# Multi-stage build for Python/FastAPI

# Build stage
FROM python:3.11-slim as builder

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

# Production stage
FROM python:3.11-slim

WORKDIR /app

# Create non-root user
RUN addgroup --system --gid 1001 appgroup && \\
    adduser --system --uid 1001 --gid 1001 appuser

# Copy wheels and install
COPY --from=builder /app/wheels /wheels
RUN pip install --no-cache /wheels/*

# Copy application
COPY . .

# Change ownership
RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
'''

DOCKERFILE_FRONTEND_TEMPLATE = '''# Frontend Dockerfile
# Multi-stage build for React/Vite

# Build stage
FROM node:20-alpine as builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built assets
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
'''

DOCKER_COMPOSE_TEMPLATE = '''version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${{DATABASE_URL}}
      - SECRET_KEY=${{SECRET_KEY}}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${{POSTGRES_USER:-postgres}}
      - POSTGRES_PASSWORD=${{POSTGRES_PASSWORD:-postgres}}
      - POSTGRES_DB=${{POSTGRES_DB:-app}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
'''

GITHUB_ACTIONS_CI_TEMPLATE = '''name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: |
          cd backend
          pytest --cov=app --cov-report=xml

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm test -- --coverage

  build:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker compose build
'''


# ============================================================================
# Code Generator Class
# ============================================================================

class CodeGenerator:
    """Utilities for code generation and template application."""

    def apply_backend_main_template(
        self,
        module_name: str,
        app_title: str,
        description: str,
        routers: List[str]
    ) -> str:
        """Generate FastAPI main.py file."""
        router_imports = "\n".join([
            f"from app.routers import {r}" for r in routers
        ])
        router_includes = "\n".join([
            f"app.include_router({r}.router)" for r in routers
        ])

        return BACKEND_MAIN_TEMPLATE.format(
            module_name=module_name,
            app_title=app_title,
            description=description,
            router_imports=router_imports,
            router_includes=router_includes
        )

    def apply_backend_router_template(
        self,
        router_name: str,
        description: str,
        prefix: str,
        tag: str,
        schema_imports: str,
        endpoints: str
    ) -> str:
        """Generate a FastAPI router file."""
        return BACKEND_ROUTER_TEMPLATE.format(
            router_name=router_name,
            description=description,
            prefix=prefix,
            tag=tag,
            schema_imports=schema_imports,
            endpoints=endpoints
        )

    def apply_frontend_component_template(
        self,
        component_name: str,
        description: str,
        imports: str,
        props_interface: str,
        props_destructure: str,
        component_body: str
    ) -> str:
        """Generate a React component file."""
        return FRONTEND_COMPONENT_TEMPLATE.format(
            component_name=component_name,
            description=description,
            imports=imports,
            props_interface=props_interface,
            props_destructure=props_destructure,
            component_body=component_body
        )

    def apply_pytest_template(
        self,
        module_name: str,
        imports: str,
        fixtures: str,
        test_classes: str
    ) -> str:
        """Generate a pytest test file."""
        return PYTEST_TEMPLATE.format(
            module_name=module_name,
            imports=imports,
            fixtures=fixtures,
            test_classes=test_classes
        )

    def get_dockerfile_backend(self) -> str:
        """Get the backend Dockerfile template."""
        return DOCKERFILE_BACKEND_TEMPLATE

    def get_dockerfile_frontend(self) -> str:
        """Get the frontend Dockerfile template."""
        return DOCKERFILE_FRONTEND_TEMPLATE

    def get_docker_compose(self) -> str:
        """Get the docker-compose template."""
        return DOCKER_COMPOSE_TEMPLATE

    def get_github_actions_ci(self) -> str:
        """Get the GitHub Actions CI template."""
        return GITHUB_ACTIONS_CI_TEMPLATE

    def ensure_imports(self, code: str, imports: List[str]) -> str:
        """Ensure required imports are present in code."""
        existing_imports = set()
        lines = code.split('\n')

        for line in lines:
            stripped = line.strip()
            if stripped.startswith('import ') or stripped.startswith('from '):
                existing_imports.add(stripped)

        missing_imports = [i for i in imports if i not in existing_imports]

        if missing_imports:
            import_block = '\n'.join(missing_imports)
            return import_block + '\n\n' + code

        return code

    def extract_json_from_response(self, response: str) -> Optional[Dict[str, Any]]:
        """
        Extract JSON from an LLM response that may contain markdown code blocks.

        Returns:
            Parsed JSON dict or None if extraction fails.
        """
        import json

        # Try to find JSON in code blocks first
        json_patterns = [
            r'```json\s*([\s\S]*?)\s*```',
            r'```\s*([\s\S]*?)\s*```',
            r'\{[\s\S]*\}'
        ]

        for pattern in json_patterns:
            matches = re.findall(pattern, response)
            for match in matches:
                try:
                    return json.loads(match)
                except json.JSONDecodeError:
                    continue

        # Try parsing the whole response as JSON
        try:
            return json.loads(response)
        except json.JSONDecodeError:
            return None

    def sanitize_filename(self, name: str) -> str:
        """Convert a name to a valid filename."""
        # Replace spaces and special chars with underscores
        sanitized = re.sub(r'[^\w\-.]', '_', name.lower())
        # Remove multiple underscores
        sanitized = re.sub(r'_+', '_', sanitized)
        return sanitized.strip('_')
